### ISSUE TITLE
Text in diff tab is illegible because of font color.

### ISSUE THREAD

**Issue by krishnaraj** [MenWhoRust/TomorrowNightTheme#17]
<img width="618" alt="Screenshot 2021-06-27 at 8 05 19 PM" src="https://user-images.githubusercontent.com/141018/123548851-1d2bd980-d784-11eb-94e9-42944e4ce3ea.png">

**Comment by MenWhoRust** [comment]
Thanks for opening the issue, fixed in 5126807e142d13a78a9b3ac0b042476f0aba1346
