### ISSUE TITLE
InteleJ IDEA 2023.1 support

### ISSUE THREAD

**Issue by Arkady-Dymkov** [MenWhoRust/TomorrowNightTheme#27]

**Comment by MenWhoRust** [comment]
Updated version codes, will be available when JetBrains approves the release

**Comment by MenWhoRust** [comment]
if you do not wish to wait, [v0.0.19](https://github.com/MenWhoRust/TomorrowNightTheme/releases/tag/v0.0.19)

**Comment by MenWhoRust** [comment]
Nevermind, publish failed, fill fix by end of today SAST time

**Comment by MenWhoRust** [comment]
fixed and awaiting review from Jetbrains
