### ISSUE TITLE
white background

### ISSUE THREAD

**Issue by Reodia** [MenWhoRust/TomorrowNightTheme#32]
![изображение](https://github.com/MenWhoRust/TomorrowNightTheme/assets/18675615/5650c405-edbc-4b92-9cd5-988689c7a405)

After updating have white background.
PyCharm 2023.3.1 (Professional Edition)
Build #PY-233.11799.298, built on December 12, 2023
Version plugin - 0.0.26

**Comment by MenWhoRust** [comment]
Tested on my side with fresh pycharm installation and issue does not appear on my side, please try and switching themes and switching back to Tomorrow Night and see if it fixes the issue
